name: Build Examples with PlatformIO

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        example:
          [
            examples/now/,
            examples/temperature/,
            examples/adjust/,
            examples/PCsync/
          ]

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Set up Python
        uses: actions/setup-python@v2.3.2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Run PlatformIO
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
        run: |
          platformio ci --lib="." --board=mayfly
